---------------------------------------------------------------
-- User Defined Reports
--------------------------------------------------------------

-- 1. Branch Level Accounts Report
SELECT
    B.BRANCH_NAME,
    AT.ACCOUNT_TYPE,
    SUM(A.BALANCE)
FROM
    BRANCH B
    JOIN ACCOUNTS A ON B.BRANCH_ID = A.BRANCH_ID
    JOIN CUSTOMER C ON C.CUSTOMER_ID = A.CUSTOMER_ID
    JOIN ACCOUNT_TYPE AT ON A.ACCOUNT_TYPE = AT.ACCOUNT_TYPE_ID
GROUP BY
    B.BRANCH_NAME, AT.ACCOUNT_TYPE;
/

-- 2. Branch Level Loan Report
SELECT
    B.BRANCH_NAME,
    LT.LOAN_TYPE,
    SUM(L.AMOUNT),
    AVG(L.TERM_IN_MONTHS)
FROM
    BRANCH B
    JOIN ACCOUNTS A ON B.BRANCH_ID = A.BRANCH_ID
    JOIN CUSTOMER C ON C.CUSTOMER_ID = A.CUSTOMER_ID
    JOIN LOAN L ON L.CUSTOMER_ID = C.CUSTOMER_ID
    JOIN LOAN_TYPE LT ON LT.LOAN_TYPE_ID = L.LOAN_TYPE
GROUP BY
    B.BRANCH_NAME, LT.LOAN_TYPE;
/

-- 3. Branch Level Transaction Report
SELECT
    B.BRANCH_NAME,
    TT.TRANSACTION_TYPE,
    SUM(T.AMOUNT)
FROM
    BRANCH B
    JOIN ACCOUNTS A ON B.BRANCH_ID = A.BRANCH_ID
    JOIN TRANSACTION_TABLE T ON A.ACCOUNT_ID = T.ACCOUNT_ID
    JOIN TRANSACTION_TYPE TT ON T.TRANSACTION_TYPE = TT.TRANSACTION_TYPE_ID
GROUP BY
    B.BRANCH_NAME, TT.TRANSACTION_TYPE;
/

-- 4.